In [1]:
import pandas as pd
import numpy as np

In [3]:
cars = pd.read_excel(r"C:\Users\jainmiahsk\Desktop\cars.xlsx")
cars.head()

Car Model  Mileage  Sell Price($)  Age(yrs)
0    BMW X5    69000          18000         6
1    BMW X5    35000          34000         3
2    BMW X5    57000          26100         5
3    BMW X5    22500          40000         2
4    BMW X5    46000          31500         4

In [4]:
#using labelencoder and Onehotencoding for dummy variables
from sklearn.preprocessing import LabelEncoder

In [5]:
le = LabelEncoder()

In [7]:
cars['Car Model'] = le.fit_transform(cars['Car Model'])

In [8]:
cars.head()

Car Model  Mileage  Sell Price($)  Age(yrs)
0          1    69000          18000         6
1          1    35000          34000         3
2          1    57000          26100         5
3          1    22500          40000         2
4          1    46000          31500         4

In [32]:
X = cars[['Car Model','Mileage','Age(yrs)']]
X

Car Model  Mileage  Age(yrs)
0           1    69000         6
1           1    35000         3
2           1    57000         5
3           1    22500         2
4           1    46000         4
5           0    59000         5
6           0    52000         5
7           0    72000         6
8           0    91000         8
9           2    67000         6
10          2    83000         7
11          2    79000         7
12          2    59000         5

In [33]:
y = cars['Sell Price($)']
y.head()

0    18000
1    34000
2    26100
3    40000
4    31500
Name: Sell Price($), dtype: int64

In [34]:
#importing OneHotEncoder
from sklearn.preprocessing import OneHotEncoder

In [35]:
ohe = OneHotEncoder(categorical_features=[0])

In [38]:
X = ohe.fit_transform(X).toarray()

In [40]:
X = X[:,1:]
X

array([[1.00e+00, 0.00e+00, 6.90e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 3.50e+04, 3.00e+00],
       [1.00e+00, 0.00e+00, 5.70e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 2.25e+04, 2.00e+00],
       [1.00e+00, 0.00e+00, 4.60e+04, 4.00e+00],
       [0.00e+00, 0.00e+00, 5.90e+04, 5.00e+00],
       [0.00e+00, 0.00e+00, 5.20e+04, 5.00e+00],
       [0.00e+00, 0.00e+00, 7.20e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 9.10e+04, 8.00e+00],
       [0.00e+00, 1.00e+00, 6.70e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 8.30e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 7.90e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 5.90e+04, 5.00e+00]])

In [47]:
#Importing Linear Regression ALgo
from sklearn import linear_model

In [48]:
reg = linear_model.LinearRegression()
reg.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [49]:
reg.predict([[1,0,69000,6]])

array([18705.2723644])

In [53]:
#importing joblib file to save and run in future
from sklearn.externals import joblib

In [54]:
joblib.dump(reg,'reg_joblib')

['reg_joblib']

In [56]:
reg_model = joblib.load('reg_joblib')

In [58]:
reg_model.predict([[0,0,45000,4]])

array([34537.77647335])

In [59]:
reg_model.predict([[0,1,86000,7]])

array([17818.95045785])

In [60]:
reg_model.score(X,y)

0.9417050937281083