In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
pd.set_option('display.max.rows',100)
pd.set_option('display.max.columns',20000)
pd.set_option('display.max.colwidth',100)

In [2]:
hr = pd.read_csv(r"C:\Users\jainmiahsk\Desktop\HR_comma_sep.csv")
hr.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years Department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [3]:
hr.shape

(14999, 10)

In [4]:
#importing pandas profiling
import pandas_profiling

In [5]:
pandas_profiling.ProfileReport(pd.read_csv(r"C:\Users\jainmiahsk\Desktop\HR_comma_sep.csv"))

In [6]:
hr.dtypes

satisfaction_level       float64
last_evaluation          float64
number_project             int64
average_montly_hours       int64
time_spend_company         int64
Work_accident              int64
left                       int64
promotion_last_5years      int64
Department                object
salary                    object
dtype: object

In [7]:
hr.Department.unique()

array(['sales', 'accounting', 'hr', 'technical', 'support', 'management',
       'IT', 'product_mng', 'marketing', 'RandD'], dtype=object)

In [8]:
hr.Department.value_counts()

sales          4140
technical      2720
support        2229
IT             1227
product_mng     902
marketing       858
RandD           787
accounting      767
hr              739
management      630
Name: Department, dtype: int64

In [9]:
hr.salary.unique()

array(['low', 'medium', 'high'], dtype=object)

In [10]:
hr.salary.value_counts()

low       7316
medium    6446
high      1237
Name: salary, dtype: int64

In [11]:
X = hr.drop('left',axis=1)
X.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  promotion_last_5years Department  salary  
0                   3              0                      0      sales     low  
1                   6              0                      0      sales  medium  
2                   4              0                      0      sales  medium  
3                   5              0                      0      sales     low  
4                   3              0                      0      sales     low

In [12]:
y = hr.left
y.head()

0    1
1    1
2    1
3    1
4    1
Name: left, dtype: int64

In [13]:
#importing Label and OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [14]:
le = LabelEncoder()
X['Department'] = le.fit_transform(X['Department'])

In [15]:
le = LabelEncoder()
X['salary'] = le.fit_transform(X['salary'])

In [16]:
X.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  promotion_last_5years  Department  \
0                   3              0                      0           7   
1                   6              0                      0           7   
2                   4              0                      0           7   
3                   5              0                      0           7   
4                   3              0                      0           7   

   salary  
0       1  
1       2  
2       2  
3       1  
4       1

In [17]:
#ohe = OneHotEncoder(categorical_features=[7,8])
#X = ohe.fit_transform(X).toarray()
#X

In [18]:
X.shape

(14999, 9)

In [19]:
#Import train test split
from sklearn.model_selection import train_test_split

In [20]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

In [21]:
#Importing Logistic Regression
from sklearn.linear_model import LogisticRegression

In [22]:
lg = LogisticRegression()
lg.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [23]:
lg.predict(X_test)

array([1, 1, 0, ..., 0, 0, 0], dtype=int64)

In [24]:
lg.score(X_test,y_test)

0.7682222222222223

In [25]:
lg.predict_proba(X_test)

array([[0.47696139, 0.52303861],
       [0.40889801, 0.59110199],
       [0.65334145, 0.34665855],
       ...,
       [0.87773701, 0.12226299],
       [0.93927818, 0.06072182],
       [0.87998837, 0.12001163]])

In [26]:
#Saving file to joblib
from sklearn.externals import joblib

In [27]:
joblib.dump(lg,'lg_joblib')

['lg_joblib']

In [28]:
lg_joblib = joblib.load('lg_joblib')

In [29]:
lg_joblib.intercept_

array([-0.0378315])

In [30]:
lg_joblib.coef_

array([[-4.07341777,  0.69028827, -0.30188149,  0.00439574,  0.22418661,
        -1.41160721, -1.31166078,  0.04032584,  0.01633705]])