In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import statistics as st

In [2]:
salary = pd.read_excel(r"C:\Users\jainmiahsk\Desktop\salary.xlsx")
salary.head()

experience  test_score  interview  salary($)
0        NaN         8.0          9      50000
1        NaN         8.0          6      45000
2       five         6.0          7      60000
3        two        10.0         10      65000
4      seven         9.0          6      70000

In [3]:
salary.experience = salary['experience'].fillna(value='zero')
salary.head(10)

experience  test_score  interview  salary($)
0       zero         8.0          9      50000
1       zero         8.0          6      45000
2       five         6.0          7      60000
3        two        10.0         10      65000
4      seven         9.0          6      70000
5      three         7.0         10      62000
6        ten         NaN          7      72000
7     eleven         7.0          8      80000

In [4]:
from word2number import w2n

In [5]:
salary.experience = salary.experience.apply(w2n.word_to_num)
salary

experience  test_score  interview  salary($)
0           0         8.0          9      50000
1           0         8.0          6      45000
2           5         6.0          7      60000
3           2        10.0         10      65000
4           7         9.0          6      70000
5           3         7.0         10      62000
6          10         NaN          7      72000
7          11         7.0          8      80000

In [6]:
salary.test_score = salary.test_score.fillna(value = 7)
salary

experience  test_score  interview  salary($)
0           0         8.0          9      50000
1           0         8.0          6      45000
2           5         6.0          7      60000
3           2        10.0         10      65000
4           7         9.0          6      70000
5           3         7.0         10      62000
6          10         7.0          7      72000
7          11         7.0          8      80000

In [7]:
X = salary.iloc[:,:-1]
X.head()

experience  test_score  interview
0           0         8.0          9
1           0         8.0          6
2           5         6.0          7
3           2        10.0         10
4           7         9.0          6

In [8]:
y = salary.iloc[:,3:]
y.head()

salary($)
0      50000
1      45000
2      60000
3      65000
4      70000

In [9]:
from sklearn import linear_model

In [10]:
reg = linear_model.LinearRegression()
reg.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [11]:
reg.predict([[2,9,6]])

array([[53713.86677124]])

In [12]:
reg.predict([[12,10,10]])

array([[93747.79628651]])

In [13]:
#Importing joblib libraries for saving file to reuse
from sklearn.externals import joblib

In [14]:
joblib.dump(reg,'reg_model')

['reg_model']

In [15]:
mul_reg_file = joblib.load('reg_model')

In [16]:
mul_reg_file.predict([[3,5,1]])

array([[37013.48655607]])